plugin:
    resource_actions:
        # the value come from the MaskDecoder Entity
        # specific menus for a resource
        - name: compose
          is_form: false
          is_async: false
          is_custom: true
          group: activity
          class: activity-class
          resource_type: activity
          value: 8

        - name: update_file
          is_form: false
          is_async: true
          is_custom: true
          group: core
          class: file-class
          resource_type: file
          value: 8

        # generic actions
        - name: export
          is_form: false
          is_async: true
          is_custom: false
          group: core
          class: changeme
          value: 4

        - name: delete
          is_form: false
          is_async: true
          is_custom: false
          group: core
          class: changeme
          value: 16

        - name: edit-rights
          is_form: true
          is_async: true
          is_custom: false
          group: core
          class: changeme
          value: 32

        - name: open-tracking
          is_form: false
          is_async: true
          is_custom: false
          group: core
          class: changeme
          value: 32

        - name: rename
          is_form: true
          is_async: true
          is_custom: false
          group: core
          class: changeme
          value: 32

        - name: edit-properties
          is_form: true
          is_async: true
          is_custom: false
          group: core
          class: changeme
          value: 32

    resources:
        - class: Claroline\CoreBundle\Entity\Resource\File
          name: file
          is_exportable: true
          activity_rules:
            - action: resource-read

        - class: Claroline\CoreBundle\Entity\Resource\Directory
          name: directory
          is_exportable: true

        - class: Claroline\CoreBundle\Entity\Resource\Text
          name: text
          is_exportable: true

        - class: Claroline\CoreBundle\Entity\Resource\ResourceShortcut
          name: resource_shortcut
          is_exportable: false

        - class: Claroline\CoreBundle\Entity\Resource\Activity
          name: activity
          is_exportable: false

    admin_tools:
        - name: platform_parameters
          class: cog
        - name: user_management
          class: user
        - name: workspace_management
          class: book
        - name: registration_to_workspace
          class: book
        - name: desktop_and_home
          class: home
        - name: platform_logs
          class: bars
        - name: platform_analytics
          class: bar-chart-o
        - name: roles_management
          class: users
        - name: widgets_management
          class: list-alt
        - name: organization_management
          class: building

    widgets:
        - name: core_resource_logger
          is_configurable: true
          is_displayable_in_desktop: true
          is_displayable_in_workspace: true
        - name: simple_text
          is_configurable: true
          is_displayable_in_desktop: true
          is_displayable_in_workspace: true
        - name: my_workspaces
          is_configurable: false
          is_displayable_in_desktop: true
          is_displayable_in_workspace: false
        - name: my_profile
          is_configurable: false
          is_displayable_in_desktop: true
          is_displayable_in_workspace: false
        - name: resources_widget
          is_configurable: true
          is_displayable_in_desktop: true
          is_displayable_in_workspace: true
