plugin:
    resource_actions:
        # the value come from the MaskDecoder Entity
        # specific menus for a resource
        - name: compose
          is_form: false
          is_async: false
          is_custom: true
          group: activity
          class: activity-class
          resource_type: activity
          value: 8

        - name: update_file
          is_form: false
          is_async: true
          is_custom: true
          group: core
          class: file-class
          resource_type: file
          value: 8

        # generic actions

        - name: export
          is_form: false
          is_async: true
          is_custom: false
          group: core
          class: changeme
          value: 4

        - name: delete
          is_form: false
          is_async: true
          is_custom: false
          group: core
          class: changeme
          value: 16

        - name: edit-rights
          is_form: true
          is_async: true
          is_custom: false
          group: core
          class: changeme
          value: 32

        - name: open-tracking
          is_form: false
          is_async: true
          is_custom: false
          group: core
          class: changeme
          value: 32

        - name: rename
          is_form: true
          is_async: true
          is_custom: false
          group: core
          class: changeme
          value: 32

        - name: edit-properties
          is_form: true
          is_async: true
          is_custom: false
          group: core
          class: changeme
          value: 32

    resources:
        - class: Claroline\CoreBundle\Entity\Resource\File
          name: file
          is_exportable: true
          activity_rules:
            - action: resource-read

        - class: Claroline\CoreBundle\Entity\Resource\Directory
          name: directory
          is_exportable: true

        - class: Claroline\CoreBundle\Entity\Resource\Text
          name: text
          is_exportable: true

        - class: Claroline\CoreBundle\Entity\Resource\ResourceShortcut
          name: resource_shortcut
          is_exportable: false

        - class: Claroline\CoreBundle\Entity\Resource\Activity
          name: activity
          is_exportable: false
