plugin:
    resource_actions:
        # Opens a resource
        - name: open
          decoder: open

        # Displays common resources info (the one from the node)
        - name: show-info
          decoder: open

        # Exports a resource in a Claroline format (archive + manifest)
        - name: export
          group: transfer
          decoder: export
          bulk: true # The action can be executed on multiple resources at once.

        # Deletes a resource
        - name: delete
          group: management
          decoder: delete
          bulk: true # The action can be executed on multiple resources at once.

        # Changes access rights of a resource
        - name: edit-rights
          group: management
          decoder: administrate
          bulk: true # The action can be executed on multiple resources at once.

        # Changes common resources info (the one from the node)
        - name: edit-properties
          group: management
          decoder: administrate
          bulk: true # The action can be executed on multiple resources at once.

        # Changes the parent of a resource
        - name: move
          group: management
          decoder: administrate
          bulk: true # The action can be executed on multiple resources at once.

        # Displays tracking info about the resource
        - name: open-tracking
          group: log
          decoder: administrate # todo : adds it's own right

    resources:
        - name: file
          class: Claroline\CoreBundle\Entity\Resource\File
          exportable: true
          actions:
              - name: download
                decoder: export
                group: transfer

        - name: directory
          class: Claroline\CoreBundle\Entity\Resource\Directory
          exportable: true
          actions:
              - name: create
                decoder: create
                group: management

        - name: text
          class: Claroline\CoreBundle\Entity\Resource\Text
          exportable: true

        - name: resource_shortcut
          class: Claroline\CoreBundle\Entity\Resource\ResourceShortcut

        - name: activity
          class: Claroline\CoreBundle\Entity\Resource\Activity

    admin_tools:
        - name: platform_parameters
          class: cog

        - name: user_management
          class: users

        - name: workspace_management
          class: book

        - name: registration_to_workspace
          class: book

        - name: desktop_and_home
          class: home

        - name: platform_logs
          class: bars

        - name: platform_analytics
          class: bar-chart-o

        - name: widgets_management
          class: list-alt

        - name: tasks_scheduling
          class: clock-o

        - name: data_transfer
          class: exchange

    widgets:
        #- name: core_resource_logger
        #      is_configurable: true
        #      is_displayable_in_desktop: true
        #      is_displayable_in_workspace: true
        #- name: simple_text
        #      is_configurable: true
        #      is_displayable_in_desktop: true
        #      is_displayable_in_workspace: true
        #- name: my_workspaces
        #      is_configurable: false
        #      is_displayable_in_desktop: true
        #      is_displayable_in_workspace: false
        #- name: my_profile
        #      is_configurable: false
        #      is_displayable_in_desktop: true
        #      is_displayable_in_workspace: false
        #- name: resources_widget
        #      is_configurable: true
        #      is_displayable_in_desktop: true
        #      is_displayable_in_workspace: true
        #- name: resource_text
        #      is_configurable: true
        #      is_displayable_in_desktop: true
        #      is_displayable_in_workspace: true

        - name: simple
          class: Claroline\CoreBundle\Entity\Widget\Type\SimpleWidget
          context: [workspace, desktop]
          tags: [content]

        - name: list
          class: Claroline\CoreBundle\Entity\Widget\Type\ListWidget
          abstract: true

        - name: profile
          class: Claroline\CoreBundle\Entity\Widget\Type\ProfileWidget
          context: [workspace, desktop]
          tags: [users]

        - name: resource-list
          parent: list
          context: [workspace, desktop]
          tags: [resources]

        - name: user-list
          parent: list
          context: [workspace, desktop]
          tags: [users]

        - name: workspace-list
          parent: list
          context: [desktop]
          tags: [workspaces]

    tools:
        - name: home
          class: home
          is_displayable_in_workspace: true
          is_displayable_in_desktop: true
          is_configurable_in_workspace: false
          is_configurable_in_desktop: false
          is_desktop_required: false
          is_workspace_required: false
          is_exportable: true
          is_locked_for_admin: false
          is_anonymous_excluded: false
        - name: parameters
          class: cog
          is_displayable_in_workspace: true
          is_displayable_in_desktop: true
          is_configurable_in_workspace: false
          is_configurable_in_desktop: false
          is_desktop_required: false
          is_workspace_required: false
          is_exportable: false
          is_locked_for_admin: true
          is_anonymous_excluded: true
        - name: resource_manager
          class: folder-open
          is_displayable_in_workspace: true
          is_displayable_in_desktop: true
          is_configurable_in_workspace: true
          is_configurable_in_desktop: false
          is_desktop_required: false
          is_workspace_required: false
          is_exportable: true
          is_locked_for_admin: false
          is_anonymous_excluded: false
        - name: logs
          class: list
          is_displayable_in_workspace: true
          is_displayable_in_desktop: false
          is_configurable_in_workspace: false
          is_configurable_in_desktop: false
          is_desktop_required: false
          is_workspace_required: false
          is_exportable: false
          is_locked_for_admin: false
          is_anonymous_excluded: true
        - name: analytics
          class: bar-chart-o
          is_displayable_in_workspace: true
          is_displayable_in_desktop: false
          is_configurable_in_workspace: false
          is_configurable_in_desktop: false
          is_desktop_required: false
          is_workspace_required: false
          is_exportable: false
          is_locked_for_admin: false
          is_anonymous_excluded: true
        - name: users
          class: user
          is_displayable_in_workspace: true
          is_displayable_in_desktop: false
          is_configurable_in_workspace: false
          is_configurable_in_desktop: false
          is_desktop_required: false
          is_workspace_required: true
          is_exportable: false
          is_locked_for_admin: false
          is_anonymous_excluded: true
        - name: my_contacts
          class: address-book
          is_displayable_in_workspace: false
          is_displayable_in_desktop: true
          is_configurable_in_workspace: false
          is_configurable_in_desktop: false
          is_desktop_required: false
          is_workspace_required: false
          is_exportable: false
          is_locked_for_admin: false
          is_anonymous_excluded: true

    themes:
        - name: Claroline
        - name: Claroline Black
        - name: Claroline Mint
        - name: Claroline Ruby
