claro_security_login_check:
    path: /login_check
    options: { expose: true }

claro_security_logout:
    path: /logout
    options: { expose: true }

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

claro_redirect:
    resource: "@ClarolineCoreBundle/Controller/RedirectController.php"
    type: annotation

claro_authentication:
    resource: "@ClarolineCoreBundle/Controller/AuthenticationController.php"
    type: annotation

claro_user_registration:
    resource: "@ClarolineCoreBundle/Controller/User/RegistrationController.php"
    type: annotation
    options: { expose: true }

claro_user_tracking:
    resource: "@ClarolineCoreBundle/Controller/User/TrackingController.php"
    type: annotation
    options: { expose: true }

claro_desktop:
    resource: "@ClarolineCoreBundle/Controller/DesktopController.php"
    type: annotation

claro_workspace:
    resource: "@ClarolineCoreBundle/Controller/WorkspaceController.php"
    type: annotation

claro_admin:
    resource: "@ClarolineCoreBundle/Controller/AdministrationController.php"
    type: annotation

claro_resource:
    resource: "@ClarolineCoreBundle/Controller/ResourceController.php"
    type: annotation

claro_search:
    resource: "@ClarolineCoreBundle/Controller/SearchController.php"
    type: annotation

claro_file:
    resource: "@ClarolineCoreBundle/Controller/FileController.php"
    type: annotation
    prefix: file

claro_admin_resource_icons:
    resource: "@ClarolineCoreBundle/Controller/Administration/IconController.php"
    prefix: admin/parameters/appearance/icon
    type: annotation

claro_admin_archives:
    resource: "@ClarolineCoreBundle/Controller/Administration/ArchiveController.php"
    prefix: archive
    type: annotation
    options:
        expose: true

claro_new_api:
    resource: "@ClarolineCoreBundle/Controller/APINew/"
    prefix: apiv2
    type: api
    options:
        expose: true
