claro_app:
    resource: "@ClarolineAppBundle/Controller/Platform/ClientController.php"
    type: annotation
    options: { expose: true }

claro_security:
    resource: "@ClarolineAppBundle/Controller/Platform/SecurityController.php"
    type: annotation
    options: { expose: true }

claro_locale:
    resource: "@ClarolineAppBundle/Controller/Platform/LocaleController.php"
    type: annotation
    options: { expose: true }
