imports:
    - { resource: services/controller.yml }
  # - { resource: services/finder.yml }
    - { resource: services/manager.yml }
    - { resource: services/adapter.yml }
    - { resource: services/persistence.yml }
    - { resource: services/routing.yml }

services:
    _defaults:
        autowire: false #change to true
        autoconfigure: false
        public: true #because controller

    Claroline\AppBundle\API\FinderProvider:
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\AppBundle\API\SerializerProvider'

    Claroline\AppBundle\API\Crud:
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\AppBundle\Event\StrictDispatcher'
            - '@Claroline\AppBundle\API\SerializerProvider'
            - '@Claroline\AppBundle\API\ValidatorProvider'
            - '@Claroline\AppBundle\API\SchemaProvider'
            - '@security.authorization_checker'

    Claroline\AppBundle\API\SchemaProvider:
        arguments:
            - '%kernel.root_dir%'
            - '@Claroline\AppBundle\API\SerializerProvider'

    Claroline\AppBundle\API\SerializerProvider:
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '%kernel.root_dir%'

    Claroline\AppBundle\API\TransferProvider:
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\AppBundle\API\SerializerProvider'
            - '@Claroline\AppBundle\API\SchemaProvider'
            - '%claroline.param.import_log_dir%'
            - '@translator'

    Claroline\AppBundle\API\ValidatorProvider:
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\AppBundle\API\SchemaProvider'

    Claroline\AppBundle\Listener\ApiListener:
        arguments:
            - '@security.token_storage'
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onError, priority: 99 }

    Claroline\AppBundle\Command\AsyncCommand:
        arguments:
            - '%kernel.root_dir%'

    Claroline\AppBundle\Persistence\ObjectManager:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@logger'

    Claroline\AppBundle\Event\StrictDispatcher:
        arguments:
            - '@event_dispatcher'

    Claroline\AppBundle\Routing\ApiLoader:
        tags: ['routing.loader']
        arguments:
            - '@file_locator'
            - '@annotation_reader'
            - '@service_container'
