# imports:
#   - { resource: services/controller.yml }
#   - { resource: services/finder.yml }


services:
    _defaults:
        autowire: false #change to true
        autoconfigure: false
        public: true #because controller

    Claroline\AppBundle\API\FinderProvider:
        arguments:
            - '@claroline.persistence.object_manager'
            - '@claroline.api.serializer'

    claroline.api.finder:
        alias: Claroline\AppBundle\API\FinderProvider
        public: true
