imports:
  # - { resource: services/controller.yml }
  # - { resource: services/finder.yml }
    - { resource: services/manager.yml }
    - { resource: services/adapter.yml }
    - { resource: services/persistence.yml }
    - { resource: services/routing.yml }

services:
    _defaults:
        autowire: false #change to true
        autoconfigure: false
        public: true #because controller

    Claroline\AppBundle\API\FinderProvider:
        arguments:
            - '@claroline.persistence.object_manager'
            - '@claroline.api.serializer'

    claroline.api.finder:
        alias: Claroline\AppBundle\API\FinderProvider
        public: true

    Claroline\AppBundle\API\Crud:
        arguments:
            - '@claroline.persistence.object_manager'
            - '@claroline.event.event_dispatcher'
            - '@claroline.api.serializer'
            - '@claroline.api.validator'
            - '@claroline.api.schema'
            - '@security.authorization_checker'

    claroline.api.crud:
        alias: Claroline\AppBundle\API\Crud
        public: true

    Claroline\AppBundle\API\SchemaProvider:
        arguments:
            - '%kernel.root_dir%'
            - '@claroline.api.serializer'

    claroline.api.schema:
        alias: Claroline\AppBundle\API\SchemaProvider
        public: true

    Claroline\AppBundle\API\SerializerProvider:
        arguments:
            - '@claroline.persistence.object_manager'
            - '%kernel.root_dir%'

    claroline.api.serializer:
        alias: Claroline\AppBundle\API\SerializerProvider
        public: true

    Claroline\AppBundle\API\TransferProvider:
        arguments:
            - '@claroline.persistence.object_manager'
            - '@claroline.api.serializer'
            - '@claroline.api.schema'
            - '%claroline.param.import_log_dir%'
            - '@translator'

    claroline.api.transfer:
        alias: Claroline\AppBundle\API\TransferProvider
        public: true

    Claroline\AppBundle\API\ValidatorProvider:
        arguments:
            - '@claroline.persistence.object_manager'
            - '@claroline.api.schema'

    claroline.api.validator:
        alias: Claroline\AppBundle\API\ValidatorProvider
        public: true

    Claroline\AppBundle\API\Listener\ApiListener:
        arguments:
            - '@security.token_storage'
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onError, priority: 99 }
            - { name: kernel.event_listener, event: kernel.response, method: onResponse }
