language: php

php:
  - "5.5"

env:
  - DB=mysql

mysql:
  adapter: mysql2
  database: claroline_test
  username: root
  encoding: utf8

before_script:
  # keep a list of files impacted by the PR
  - git diff-tree --no-commit-id --diff-filter=ACM --name-only -r ${TRAVIS_COMMIT_RANGE/.../ } > git_diff_files.txt

  # leave build/repo dir
  - cd ../..

  # increase php memory size (required for composer)
  - echo "memory_limit=3072M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  # disable xdebug
  - phpenv config-rm xdebug.ini

  # get node >=5.6
  - git clone https://github.com/creationix/nvm.git /tmp/.nvm
  - source /tmp/.nvm/nvm.sh
  - nvm install 5
  - nvm use --delete-prefix 5

  # get and configure claroline platform
  - curl -L https://github.com/claroline/Claroline/archive/monolithic-build.tar.gz | tar xzv
  - cd Claroline-monolithic-build
  - php scripts/configure.php --default

  # override platform composer.json with build/repo local reference
  - rm -rf ../$TRAVIS_REPO_SLUG/.git
  - php ../$TRAVIS_REPO_SLUG/main/dev/Resources/travis/pre-composer.php claroline/distribution ../$TRAVIS_REPO_SLUG

  # fetch dependencies and build
  - composer self-update
  - composer update --prefer-source
  - npm install
  - npm run bower
  - composer build
  - php app/console claroline:install --env=test

script:
  - cd vendor/claroline/distribution
  - ../../../bin/phpmd --exclude main/core/Resources/bundle-creator,main/web-installer `cat git_diff_files.txt | xargs | sed -e :a -e '$!N; s/ /,/; ta'` text phpmd.xml
  - ../../../bin/php-cs-fixer fix --dry-run --diff --config-file=main/dev/Resources/travis/php-cs.php -vvv
  - SYMFONY_DEPRECATIONS_HELPER=weak ../../../bin/phpunit
