services:
    _defaults:
        autowire: false #change to true
        autoconfigure: false
        public: true #because controller

    _instanceof:
        Claroline\AppBundle\Controller\AbstractCrudController:
            calls:
              - method: setFinder
                arguments:
                  - '@Claroline\AppBundle\API\FinderProvider'
              - method: setSerializer
                arguments:
                  - '@Claroline\AppBundle\API\SerializerProvider'
              - method: setCrud
                arguments:
                  - '@Claroline\AppBundle\API\Crud'
              - method: setObjectManager
                arguments:
                  - '@Claroline\AppBundle\Persistence\ObjectManager'
              - method: setRouterFinder
                arguments:
                  - '@Claroline\AppBundle\Routing\Finder'
              - method: setRouterDocumentator
                arguments:
                  - '@Claroline\AppBundle\Routing\Documentator'
              - method: setContainer
                arguments:
                  - '@service_container'

    Claroline\BigBlueButtonBundle\Controller\BBBController:
        arguments:
            - '@security.authorization_checker'
            - '@Claroline\BigBlueButtonBundle\Manager\BBBManager'
            - '@claroline.manager.curl_manager'
            - '@Claroline\CoreBundle\API\Serializer\ParametersSerializer'
            - '@router'
            - '@claroline.manager.tool_manager'
            - '@Claroline\CoreBundle\Library\RoutingHelper'
