services:
    _defaults:
        autowire: false #change to true
        autoconfigure: false
        public: true

    Claroline\BigBlueButtonBundle\Configuration\PlatformDefaults:
        tags: ['claroline.configuration']
