services:
    _defaults:
        autowire: false #change to true
        autoconfigure: false
        public: true

    Claroline\BigBlueButtonBundle\Manager\ServerManager:
        arguments:
            - '@security.token_storage'
            - '@Claroline\CoreBundle\Library\Configuration\PlatformConfigurationHandler'
            - '@claroline.manager.curl_manager'

    Claroline\BigBlueButtonBundle\Manager\BBBManager:
        arguments:
            - '@security.token_storage'
            - '@translator'
            - '@Claroline\CoreBundle\Library\Configuration\PlatformConfigurationHandler'
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\AppBundle\API\SerializerProvider'
            - '@claroline.manager.curl_manager'
            - '@Claroline\CoreBundle\Library\RoutingHelper'
            - '@Claroline\BigBlueButtonBundle\Manager\ServerManager'
