services:
    _defaults:
        autowire: false #change to true
        autoconfigure: false
        public: true
        tags: ['claroline.serializer']

    Claroline\BigBlueButtonBundle\Serializer\BBBSerializer: ~
