services:
    _defaults:
        autowire: false #change to true
        autoconfigure: false
        public: true
        tags: ['claroline.serializer']

    Claroline\BigBlueButtonBundle\Serializer\BBBSerializer:
        arguments:
            - '@Claroline\CoreBundle\API\Serializer\Resource\ResourceNodeSerializer'
            - '@Claroline\BigBlueButtonBundle\Manager\BBBManager'

    Claroline\BigBlueButtonBundle\Serializer\RecordingSerializer: ~
