services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    Claroline\DevBundle\Manager\TranslationManager: ~

    Claroline\DevBundle\Listener\DebugListener:
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onResponse }
