<?php

namespace UJM\ExoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ShareRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShareRepository extends EntityRepository
{
    /**
     * Allow to know if a question is shared with an user.
     *
     *
     * @param int $user     id User
     * @param int $question id Question
     *
     * Return array[Share]
     */
    public function getControlSharedQuestion($user, $question)
    {
        $qb = $this->createQueryBuilder('s');
        $qb->join('s.question', 'q')
            ->where($qb->expr()->in('q', $question))
            ->andWhere($qb->expr()->in('s.user', $user));

        return $qb->getQuery()->getResult();
    }
}
