<?php

namespace UJM\ExoBundle\Repository;

use Doctrine\ORM\EntityRepository;
use UJM\ExoBundle\Entity\Exercise;
use UJM\ExoBundle\Entity\Question\Question;
use UJM\ExoBundle\Entity\StepQuestion;

/**
 * StepQuestionRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StepQuestionRepository extends EntityRepository
{
    /**
     * Get the StepQuestion that links the Question to an Exercise.
     *
     * @param Exercise $exercise
     * @param Question $question
     *
     * @return StepQuestion
     */
    public function findByExerciseAndQuestion(Exercise $exercise, Question $question)
    {
        return $this->createQueryBuilder('sq')
            ->join('sq.step', 's')
            ->where('s.exercise = :exercise')
            ->andWhere('sq.question = :question')
            ->setParameter(':exercise', $exercise)
            ->setParameter(':question', $question)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
