services:
    _defaults:
        autowire: false #change to true
        autoconfigure: false
        public: true #because controller

    Claroline\AuthenticationBundle\Library\LegacyParametersMapping:
        tags: ['claroline.configuration.mapping.legacy']

    Claroline\AuthenticationBundle\Library\PlatformDefaults:
        tags: ['claroline.configuration']
