services:
    _defaults:
        autowire: false #change to true
        autoconfigure: false
        public: true #because controller

    Claroline\AuthenticationBundle\Listener\UserListener:
        arguments:
            - '@Claroline\AuthenticationBundle\Manager\OauthManager'
        tags:
            - { name: kernel.event_listener, event: merge_users, method: onMerge }
            - { name: kernel.event_listener, event: log, method: onDelete }
