services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: true

    _instanceof:
        Claroline\AppBundle\API\Serializer\GenericSerializer:
            tags: [claroline.serializer]
            calls:
                - method: setAnnotationReader
                  arguments:
                     - '@annotation_reader'
                - method: setObjectManager
                  arguments:
                     - '@Claroline\AppBundle\Persistence\ObjectManager'


    Claroline\AuthenticationBundle\Serializer\OauthUserSerializer: ~
