assetic:
    debug:          %kernel.debug%
    use_controller: false
    variables:
        locale: [en, fr, es, nl, de]
    node_paths: ['%kernel.root_dir%/../node_modules']
    filters:
        cssrewrite: ~
        less: ~
