framework:
    secret:          "%secret%"
    router:
        resource: .
        type: dynamic
    form:            true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] }
    translator:      { fallback: en }
    default_locale: "%locale%"
    session:
      save_path: "%kernel.project_dir%/app/sessions"
      cookie_httponly: true
