security:
    providers:
        user_db:
            entity: { class: Claroline\CoreBundle\Entity\User }

    encoders:
        Claroline\CoreBundle\Entity\User: sha512

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        #api:
        #   pattern: ^/(api|apiv2)/
        #   stateless: true
        #   simple_preauth:
        #      authenticator: Claroline\AuthenticationBundle\Security\Authentication\ApiTokenAuthenticator

        main:
            pattern: ^/
            anonymous: ~
            logout:
                path:   /logout
                target: /
            switch_user: { role: ROLE_ALLOWED_TO_SWITCH, parameter: _switch }

            # Allows SAML authentication
            light_saml_sp:
                provider: user_db       # user provider name configured in step 9
                user_creator: 'Claroline\AuthenticationBundle\Security\Saml\UserCreator'  # name of the user creator service created in step 10
                login_path: /saml/login
                check_path: /saml/login_check
                default_target_path: /
                require_previous_session: false
                success_handler: Claroline\CoreBundle\Listener\AuthenticationSuccessListener
                failure_handler: Claroline\CoreBundle\Listener\AuthenticationFailureHandler

            # Allows IP authentication
            simple_preauth:
                authenticator: Claroline\AuthenticationBundle\Security\Authentication\IpAuthenticator

            # Allows JSON authentication
            json_login:
                check_path: /login
                success_handler: Claroline\CoreBundle\Listener\AuthenticationSuccessListener
                failure_handler: Claroline\CoreBundle\Listener\AuthenticationFailureHandler

    access_decision_manager:
        allow_if_all_abstain: false

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/saml, roles: IS_AUTHENTICATED_ANONYMOUSLY }
