security:
    providers:
        user_db:
            entity: { class: Claroline\CoreBundle\Entity\User }

    encoders:
        Claroline\CoreBundle\Entity\User: sha512

    firewalls:
        install:
            pattern: ^/install
            security: false

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
           pattern: "%firewall_api_regex%"
           stateless: true
           simple_preauth:
              authenticator: claroline.security.authentication.apitoken_authenticator

        main:
            pattern: ^/
            simple_preauth:
                authenticator: claroline.security.authentication.ip_authenticator
            json_login:
                check_path: /login
            anonymous: ~
            logout: true
            switch_user: { role: ROLE_ALLOWED_TO_SWITCH, parameter: _switch }

            remember_me:
                secret:      "%secret%"
                lifetime: 31536000 # 365 days
                path:     /
                domain:   ~

        # Won't go here unless cas bundle is present and cas is activated
        cas:
            pattern: ^/
            anonymous: ~
            switch_user: { role: ROLE_ALLOWED_TO_SWITCH, parameter: _switch }
            # Same context as main firewall to work well with api
            context: main

    access_decision_manager:
        allow_if_all_abstain: false

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect, role: IS_AUTHENTICATED_ANONYMOUSLY }
