security:
    providers:
        user_db:
            entity: { class: Claroline\CoreBundle\Entity\User }

    encoders:
        Claroline\CoreBundle\Entity\User: sha512

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        #api:
        #   pattern: ^/(api|apiv2)/
        #   stateless: true
        #   simple_preauth:
        #      authenticator: Claroline\AuthenticationBundle\Security\Authentication\ApiTokenAuthenticator

        main:
            pattern: ^/
            logout_on_user_change: true
            anonymous: ~
            logout:
                path:   /logout
                target: /
            switch_user: { role: ROLE_ALLOWED_TO_SWITCH, parameter: _switch }

            guard:
                authenticators:
                    - 'Claroline\AuthenticationBundle\Security\Authentication\Guard\IpAuthenticator'
                    - 'Claroline\AuthenticationBundle\Security\Authentication\Guard\ApiTokenAuthenticator'
                entry_point: 'Claroline\AuthenticationBundle\Security\Authentication\Guard\ApiTokenAuthenticator'

            # Allows JSON authentication
            json_login:
                check_path: /login
                success_handler: Claroline\CoreBundle\Listener\AuthenticationSuccessListener
                failure_handler: Claroline\CoreBundle\Listener\AuthenticationFailureHandler

    access_decision_manager:
        allow_if_all_abstain: false

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/saml, roles: IS_AUTHENTICATED_ANONYMOUSLY }
