security:
    providers:
        user_db:
            entity: { class: Claroline\CoreBundle\Entity\User }

    encoders:
        Claroline\CoreBundle\Entity\User: sha512

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        #api:
        #   pattern: ^/(api|apiv2)/
        #   stateless: true
        #   simple_preauth:
        #      authenticator: Claroline\CoreBundle\Security\Authentication\ApiTokenAuthenticator

        main:
            pattern: ^/
            anonymous: ~
            logout: true
            switch_user: { role: ROLE_ALLOWED_TO_SWITCH, parameter: _switch }
            # Allows IP authentication
            simple_preauth:
                authenticator: Claroline\CoreBundle\Security\Authentication\IpAuthenticator
            # Allows JSON authentication
            json_login:
                check_path: /login
                success_handler: Claroline\CoreBundle\Listener\AuthenticationSuccessListener
                failure_handler: Claroline\CoreBundle\Listener\AuthenticationFailureHandler

    access_decision_manager:
        allow_if_all_abstain: false

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect, role: IS_AUTHENTICATED_ANONYMOUSLY }
