services:
    _defaults:
        autowire: false #change to true
        autoconfigure: false
        public: true #because controller

    _instanceof:
        Claroline\AppBundle\Controller\AbstractCrudController:
            calls:
              - method: setFinder
                arguments:
                  - '@claroline.api.finder'
              - method: setSerializer
                arguments:
                  - '@claroline.api.serializer'
              - method: setCrud
                arguments:
                  - '@claroline.api.crud'
              - method: setObjectManager
                arguments:
                  - '@claroline.persistence.object_manager'
              - method: setRouterFinder
                arguments:
                  - '@Claroline\AppBundle\Routing\Finder'
              - method: setRouterDocumentator
                arguments:
                  - '@Claroline\AppBundle\Routing\Documentator'
              - method: mergeOptions
              - method: setContainer
                arguments:
                  - '@service_container'

    Claroline\AppBundle\Controller\Platform\ClientController:
        arguments:
          - '@security.token_storage'
          - '@claroline.event.event_dispatcher'
          - '@claroline.config.platform_config_handler'
          - '@claroline.api.serializer'
          - '@Claroline\CoreBundle\API\Serializer\Platform\ClientSerializer'
