services:
    _defaults:
        autowire: false #change to true
        autoconfigure: false
        public: true #because controller

    _instanceof:
        Claroline\AppBundle\API\Finder\AbstractFinder:
            calls:
                - method: setObjectManager
                  arguments:
                    - '@claroline.persistence.object_manager'
                    - '@doctrine.orm.entity_manager'
                    - '@claroline.event.event_dispatcher'
