services:
    _defaults:
        autowire: false #change to true
        autoconfigure: false
        public: true #because I don't know

    Claroline\AppBundle\Persistence\TableManager:
        arguments:
          - '@doctrine.dbal.default_connection'
