services:
    _defaults:
        autowire: false #change to true
        autoconfigure: false
        public: true #because I don't know

    Claroline\AppBundle\Routing\Finder:
        public: true
        arguments:
            - '@router'

    Claroline\AppBundle\Routing\Documentator:
        public: true
        arguments:
            - '@claroline.api.finder'
            - '@claroline.api.serializer'
            - '@Claroline\AppBundle\API\SchemaProvider'
            - '@annotation_reader'
            - '@Claroline\AppBundle\Routing\Finder'
