services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: true #because lazy
        tags: [claroline.crud]

    Claroline\CoreBundle\API\Crud\WorkspaceCrud:
        arguments:
            - '@claroline.manager.workspace_manager'
            - '@claroline.manager.user_manager'
            - '@security.token_storage'
            - '@claroline.manager.resource_manager'
            - '@claroline.manager.role_manager'
            - '@claroline.manager.organization.organization_manager'
            - '@Claroline\AppBundle\Persistence\ObjectManager'
        tags:
            - { name: kernel.event_listener, event: crud_pre_delete_object_claroline_corebundle_entity_workspace_workspace, method: preDelete }
            - { name: kernel.event_listener, event: crud_pre_create_object_claroline_corebundle_entity_workspace_workspace, method: preCreate }
            - { name: kernel.event_listener, event: crud_pre_copy_object_claroline_corebundle_entity_workspace_workspace, method: preCopy }
            - { name: kernel.event_listener, event: crud_post_update_object_claroline_corebundle_entity_workspace_workspace, method: postUpdate }

    Claroline\CoreBundle\API\Crud\User\UserCrud:
        arguments:
            - '@service_container'
        tags:
          - { name: kernel.event_listener, event: crud_pre_create_object_claroline_corebundle_entity_user, method: preCreate }
          - { name: kernel.event_listener, event: crud_pre_delete_object_claroline_corebundle_entity_user, method: preDelete }
          - { name: kernel.event_listener, event: crud_pre_update_object_claroline_corebundle_entity_user, method: preUpdate }

    claroline.crud.user:
        alias: Claroline\CoreBundle\API\Crud\User\UserCrud
        public: true

    Claroline\CoreBundle\API\Crud\User\RoleCrud:
        arguments:
            - '@Claroline\AppBundle\Event\StrictDispatcher'
            - '@doctrine.dbal.default_connection'
        tags:
          - { name: kernel.event_listener, event: crud_pre_create_object_claroline_corebundle_entity_role, method: preCreate }
          - { name: kernel.event_listener, event: crud_post_create_object_claroline_corebundle_entity_role, method: postCreate }
          - { name: kernel.event_listener, event: crud_pre_patch_object_claroline_corebundle_entity_role, method: prePatch }

    Claroline\CoreBundle\API\Crud\User\OrganizationCrud:
        arguments:
            - '@security.token_storage'
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@claroline.manager.cryptography_manager'
            - '@Claroline\AppBundle\API\Crud'
        tags:
          - { name: kernel.event_listener, event: crud_pre_create_object_claroline_corebundle_entity_organization_organization, method: preCreate }
          - { name: kernel.event_listener, event: crud_post_create_object_claroline_corebundle_entity_organization_organization, method: postCreate }
          - { name: kernel.event_listener, event: crud_pre_delete_object_claroline_corebundle_entity_organization_organization, method: preDelete }
          - { name: kernel.event_listener, event: crud_post_patch_object_claroline_corebundle_entity_organization_organization, method: postPatch }

    Claroline\CoreBundle\API\Crud\User\GroupCrud:
        arguments:
            - '@security.token_storage'
        tags:
          - { name: kernel.event_listener, event: crud_pre_create_object_claroline_corebundle_entity_group, method: preCreate }

    Claroline\CoreBundle\API\Crud\Resource\ResourceNodeCrud:
        arguments:
            - '@security.token_storage'
        tags:
          - { name: kernel.event_listener, event: crud_pre_create_object_claroline_corebundle_entity_resource_resourcenode, method: preCreate }

    Claroline\CoreBundle\API\Crud\Home\WidgetInstanceCrud:
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'
        tags:
          - { name: kernel.event_listener, event: crud_pre_delete_object_claroline_corebundle_entity_widget_widgetinstance, method: preDelete }

    claroline.crud.widget_instance:
        alias: Claroline\CoreBundle\API\Crud\Home\WidgetInstanceCrud
        public: true

    Claroline\CoreBundle\API\Crud\Home\WidgetContainerCrud:
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@claroline.crud.widget_instance'
        tags:
          - { name: kernel.event_listener, event: crud_pre_delete_object_claroline_corebundle_entity_widget_widgetcontainer, method: preDelete }

    claroline.crud.widget_container:
        alias: Claroline\CoreBundle\API\Crud\Home\WidgetContainerCrud
        public: true

    Claroline\CoreBundle\API\Crud\Home\HomeTabCrud:
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@claroline.crud.widget_container'
        tags:
          - { name: kernel.event_listener, event: crud_pre_delete_object_claroline_corebundle_entity_tab_hometab, method: preDelete }

    claroline.crud.widget_home_tab:
        alias: Claroline\CoreBundle\API\Crud\Home\HomeTabCrud
        public: true

    Claroline\CoreBundle\API\Crud\File\PublicFile:
        arguments:
            - '%claroline.param.files_directory%'
            - '@filesystem'
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '%claroline.param.public_files_directory%'
            - '@security.token_storage'
            - '@Claroline\CoreBundle\Library\Utilities\FileUtilities'
        tags:
          - { name: kernel.event_listener, event: crud_pre_create_object_claroline_corebundle_entity_file_publicfile, method: preCreate }

    Claroline\CoreBundle\API\Crud\Cryptography\ApiToken:
        arguments:
            - '@security.token_storage'
        tags:
          - { name: kernel.event_listener, event: crud_pre_create_object_claroline_corebundle_entity_cryptography_apitoken, method: preCreate }
