services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: true
        tags: [claroline.transfer.action]

    _instanceof:

        Claroline\AppBundle\API\Finder\AbstractFinder:
            tags: [claroline.finder]
            calls:
                - method: setObjectManager
                  arguments:
                     - '@claroline.persistence.object_manager'
                - method: setEntityManager
                  arguments:
                     - '@doctrine.orm.entity_manager'
                - method: setEventDispatcher
                  arguments:
                     - '@claroline.event.event_dispatcher'

    Claroline\CoreBundle\API\Finder\TransferFinder: ~

    claroline.api.finder.transfer:
        alias: Claroline\CoreBundle\API\Finder\TransferFinder
        public: true

    Claroline\CoreBundle\API\Finder\ThemeFinder: ~

    claroline.api.finder.theme:
        alias: Claroline\CoreBundle\API\Finder\ThemeFinder
        public: true

    Claroline\CoreBundle\API\Finder\Workspace\WorkspaceFinder:
        arguments:
          - '@security.authorization_checker'
          - '@security.token_storage'

    claroline.api.finder.workspace:
        alias: Claroline\CoreBundle\API\Finder\Workspace\WorkspaceFinder
        public: true

    Claroline\CoreBundle\API\Finder\PendingRegistrationFinder: ~

    claroline.api.finder.pending:
        alias: Claroline\CoreBundle\API\Finder\PendingRegistrationFinder
        public: true

    Claroline\CoreBundle\API\Finder\OrderedToolFinder: ~

    claroline.api.finder.ordered_tool:
        alias: Claroline\CoreBundle\API\Finder\OrderedToolFinder
        public: true

    Claroline\CoreBundle\API\Finder\User\UserFinder:
        arguments:
          - '@security.authorization_checker'
          - '@security.token_storage'
          - '@claroline.manager.workspace_manager'

    claroline.api.finder.user:
        alias: Claroline\CoreBundle\API\Finder\User\UserFinder
        public: true

    Claroline\CoreBundle\API\Finder\User\RoleFinder:
        arguments:
          - '@security.authorization_checker'
          - '@security.token_storage'

    claroline.api.finder.role:
        alias: Claroline\CoreBundle\API\Finder\User\RoleFinder
        public: true

    Claroline\CoreBundle\API\Finder\User\OrganizationFinder:
        arguments:
          - '@security.authorization_checker'
          - '@security.token_storage'

    claroline.api.finder.organization:
        alias: Claroline\CoreBundle\API\Finder\User\LocationFinder
        public: true

    Claroline\CoreBundle\API\Finder\User\LocationFinder: ~

    claroline.api.finder.location:
        alias: Claroline\CoreBundle\API\Finder\User\LocationFinder
        public: true

    Claroline\CoreBundle\API\Finder\User\GroupFinder:
        arguments:
          - '@security.authorization_checker'
          - '@security.token_storage'

    claroline.api.finder.group:
        alias: Claroline\CoreBundle\API\Finder\User\GroupFinder
        public: true

    Claroline\CoreBundle\API\Finder\User\FieldFacetValueFinder:
        arguments:
          - '@security.authorization_checker'
          - '@security.token_storage'

    claroline.api.finder.field_facet_value:
        alias: Claroline\CoreBundle\API\Finder\User\FieldFacetValueFinder
        public: true

    Claroline\CoreBundle\API\Finder\Tool\ToolFinder:
        arguments:
          - '@claroline.manager.plugin_manager'

    claroline.api.finder.tool:
        alias: Claroline\CoreBundle\API\Finder\Tool\ToolFinder
        public: true

    Claroline\CoreBundle\API\Finder\Tool\AdminToolFinder:
        arguments:
          - '@claroline.manager.plugin_manager'

    claroline.api.finder.admin_tool:
        alias: Claroline\CoreBundle\API\Finder\Tool\AdminToolFinder
        public: true
