services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: true
        tags: [claroline.transfer.action]

    _instanceof:

        Claroline\AppBundle\API\Finder\AbstractFinder:
            tags: [claroline.finder]
            calls:
                - method: setObjectManager
                  arguments:
                     - '@claroline.persistence.object_manager'
                - method: setEntityManager
                  arguments:
                     - '@doctrine.orm.entity_manager'
                - method: setEventDispatcher
                  arguments:
                     - '@claroline.event.event_dispatcher'

    Claroline\CoreBundle\API\Finder\TransferFinder: ~

    claroline.api.finder.transfer:
        alias: Claroline\CoreBundle\API\Finder\TransferFinder
        public: true

    Claroline\CoreBundle\API\Finder\ThemeFinder: ~

    claroline.api.finder.theme:
        alias: Claroline\CoreBundle\API\Finder\ThemeFinder
        public: true

    Claroline\CoreBundle\API\Finder\Workspace\WorkspaceFinder:
        arguments:
          - '@security.authorization_checker'
          - '@security.token_storage'

    claroline.api.finder.workspace:
        alias: Claroline\CoreBundle\API\Finder\Workspace\WorkspaceFinder
        public: true

    Claroline\CoreBundle\API\Finder\PendingRegistrationFinder: ~

    claroline.api.finder.pending:
        alias: Claroline\CoreBundle\API\Finder\PendingRegistrationFinder
        public: true

    Claroline\CoreBundle\API\Finder\OrderedToolFinder: ~

    claroline.api.finder.ordered_tool:
        alias: Claroline\CoreBundle\API\Finder\OrderedToolFinder
        public: true
