services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: true #because lazy
        tags: [claroline.crud]

    Claroline\CoreBundle\Listener\Administration\AppearanceListener:
        arguments:
            - '@Claroline\CoreBundle\API\Serializer\ParametersSerializer'
            - '@claroline.manager.icon_set_manager'
        tags:
            - { name: kernel.event_listener, event: administration_tool_appearance_settings, method: onDisplayTool }

    Claroline\CoreBundle\Listener\Administration\CommunityListener:
        arguments:
            - '@claroline.api.finder'
            - '@claroline.manager.icon_set_manager'
        tags:
            - { name: kernel.event_listener, event: administration_tool_appearance_settings, method: onDisplayTool }
