services:
    _defaults:
        autowire: false
        autoconfigure: true
        public: false

    _instanceof:
        Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository:
            autowire: false
            tags: [doctrine.repository_service]

    Claroline\CoreBundle\Repository\Tool\AdministrationToolRepository:
        arguments:
          - '@Doctrine\Persistence\ManagerRegistry'
          - '@claroline.manager.plugin_manager'

    Claroline\CoreBundle\Repository\Tool\OrderedToolRepository:
        arguments:
          - '@Doctrine\Persistence\ManagerRegistry'
          - '@claroline.manager.plugin_manager'

    Claroline\CoreBundle\Repository\ResourceActionRepository:
        arguments:
          - '@Doctrine\Persistence\ManagerRegistry'
          - '@claroline.manager.plugin_manager'

    Claroline\CoreBundle\Repository\ResourceTypeRepository:
        arguments:
          - '@Doctrine\Persistence\ManagerRegistry'
          - '@claroline.manager.plugin_manager'

    Claroline\CoreBundle\Repository\Tool\ToolRepository:
        arguments:
          - '@Doctrine\Persistence\ManagerRegistry'
          - '@claroline.manager.plugin_manager'

    Claroline\CoreBundle\Repository\UserRepository:
        arguments:
          - '@Doctrine\Persistence\ManagerRegistry'
          - '@Claroline\CoreBundle\Library\Configuration\PlatformConfigurationHandler'

    Claroline\CoreBundle\Repository\Log\LogRepository:
        arguments:
          - '@Doctrine\Persistence\ManagerRegistry'
          - '@Claroline\CoreBundle\API\Finder\Log\LogFinder'

    Claroline\CoreBundle\Repository\ResourceNodeRepository:
      arguments:
        - '@Doctrine\Persistence\ManagerRegistry'
        - '@claroline.manager.plugin_manager'
