services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    Claroline\CoreBundle\Library\Security\TokenUpdater:
        arguments:
            - '@security.token_storage'
            - '@Claroline\AppBundle\Persistence\ObjectManager'

    Claroline\CoreBundle\Library\Security\Evaluator\AdminToolAccessEvaluator:
        arguments:
            - '@security.authorization_checker'
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: security.expressions.function_evaluator, function: canOpenAdminTool }
