services:
    _defaults:
        autowire: false
        autoconfigure: true
        public: true

    _instanceof:
        Claroline\AppBundle\API\Serializer\GenericSerializer:
            calls:
                - method: setAnnotationReader
                  arguments:
                     - '@annotation_reader'
                - method: setObjectManager
                  arguments:
                     - '@Claroline\AppBundle\Persistence\ObjectManager'

    Claroline\CoreBundle\API\Serializer\ParametersSerializer:
        arguments:
          - '@Claroline\AppBundle\API\SerializerProvider'
          - '@Claroline\AppBundle\API\FinderProvider'
          - '@claroline.manager.icon_set_manager'
          - '@Claroline\AppBundle\Persistence\ObjectManager'
          - '@Claroline\CoreBundle\Library\Configuration\PlatformConfigurationHandler'
          - '%claroline.param.platform_options%'
          - '%claroline.param.archive_directory%'

    Claroline\CoreBundle\API\Serializer\ObjectLockSerializer:
        tags: [claroline.serializer]
        arguments:
          - '@Claroline\CoreBundle\API\Serializer\User\UserSerializer'

    Claroline\CoreBundle\API\Serializer\MessageSerializer:
        arguments:
          - '@Claroline\CoreBundle\API\Serializer\User\UserSerializer'
          - '@Claroline\AppBundle\Persistence\ObjectManager'

    Claroline\CoreBundle\API\Serializer\DataSourceSerializer:
        tags: [claroline.serializer]

    Claroline\CoreBundle\API\Serializer\AdminToolSerializer:
        tags: [claroline.serializer]

    Claroline\CoreBundle\API\Serializer\Workspace\WorkspaceSerializer:
        tags: [claroline.serializer]
        arguments:
          - '@security.authorization_checker'
          - '@security.token_storage'
          - '@Claroline\AppBundle\Persistence\ObjectManager'
          - '@claroline.manager.workspace_manager'
          - '@claroline.manager.resource_manager'
          - '@Claroline\CoreBundle\Library\Utilities\ClaroUtilities'
          - '@Claroline\CoreBundle\Library\Utilities\FileUtilities'
          - '@Claroline\AppBundle\API\FinderProvider'
          - '@Claroline\CoreBundle\API\Serializer\User\UserSerializer'
          - '@Claroline\CoreBundle\API\Serializer\File\PublicFileSerializer'
          - '@Claroline\CoreBundle\API\Serializer\Resource\ResourceNodeSerializer'

    Claroline\CoreBundle\API\Serializer\Workspace\ShortcutsSerializer:
        tags: [claroline.serializer]
        arguments:
            - '@Claroline\CoreBundle\API\Serializer\User\RoleSerializer'

    Claroline\CoreBundle\API\Serializer\Workspace\PendingRegistrationSerializer:
        tags: [claroline.serializer]
        arguments:
            - '@Claroline\CoreBundle\API\Serializer\User\UserSerializer'

    Claroline\CoreBundle\API\Serializer\Widget\WidgetSerializer:
        tags: [claroline.serializer]

    Claroline\CoreBundle\API\Serializer\Widget\WidgetInstanceSerializer:
        tags: [claroline.serializer]
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\AppBundle\API\SerializerProvider'

    Claroline\CoreBundle\API\Serializer\Widget\WidgetContainerSerializer:
        tags: [claroline.serializer]
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\CoreBundle\API\Finder\Home\WidgetInstanceFinder'
            - '@Claroline\CoreBundle\API\Serializer\Widget\WidgetInstanceSerializer'
            - '@Claroline\CoreBundle\API\Serializer\File\PublicFileSerializer'

    Claroline\CoreBundle\API\Serializer\Widget\HomeTabSerializer:
        tags: [claroline.serializer]
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\CoreBundle\API\Finder\Home\WidgetContainerFinder'
            - '@Claroline\CoreBundle\API\Serializer\Widget\WidgetContainerSerializer'
            - '@Claroline\CoreBundle\API\Serializer\Workspace\WorkspaceSerializer'
            - '@Claroline\CoreBundle\API\Serializer\User\UserSerializer'
            - '@Claroline\CoreBundle\API\Serializer\File\PublicFileSerializer'

    Claroline\CoreBundle\API\Serializer\Widget\Type\SimpleWidgetSerializer:
        tags: [claroline.serializer]

    Claroline\CoreBundle\API\Serializer\Widget\Type\ResourceWidgetSerializer:
        tags: [claroline.serializer]
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\CoreBundle\API\Serializer\Resource\ResourceNodeSerializer'

    Claroline\CoreBundle\API\Serializer\Widget\Type\ListWidgetSerializer:
        tags: [claroline.serializer]

    Claroline\CoreBundle\API\Serializer\User\UserSerializer:
        tags: [claroline.serializer]
        arguments:
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\CoreBundle\Library\Configuration\PlatformConfigurationHandler'
            - '@claroline.manager.facet_manager'
            - '@Claroline\CoreBundle\API\Serializer\File\PublicFileSerializer'
            - '@service_container'
            - '@Claroline\AppBundle\Event\StrictDispatcher'
            - '@Claroline\CoreBundle\API\Serializer\User\OrganizationSerializer'
            - '@Claroline\CoreBundle\API\Serializer\Facet\FieldFacetValueSerializer'

    Claroline\CoreBundle\API\Serializer\User\RoleSerializer:
        tags: [claroline.serializer]
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\CoreBundle\API\Finder\Workspace\OrderedToolFinder'
            - '@Claroline\CoreBundle\API\Serializer\Workspace\WorkspaceSerializer'
            - '@Claroline\CoreBundle\API\Serializer\User\UserSerializer'

    Claroline\CoreBundle\API\Serializer\User\ProfileSerializer:
        arguments:
            - '@security.token_storage'
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\CoreBundle\API\Serializer\Facet\FacetSerializer'

    Claroline\CoreBundle\API\Serializer\User\OrganizationSerializer:
        tags: [claroline.serializer]
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'

    Claroline\CoreBundle\API\Serializer\User\LocationSerializer:
        tags: [claroline.serializer]

    Claroline\CoreBundle\API\Serializer\User\GroupSerializer:
        tags: [claroline.serializer]
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\CoreBundle\API\Serializer\User\OrganizationSerializer'
            - '@Claroline\CoreBundle\API\Serializer\User\RoleSerializer'

    Claroline\CoreBundle\API\Serializer\Translatable\TranslatableSerializer:
        tags: [claroline.serializer]
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@claroline.manager.locale_manager'
            - '@service_container'

    Claroline\CoreBundle\API\Serializer\Transfer\FileSerializer:
        tags: [claroline.serializer]
        arguments:
           - '@Claroline\CoreBundle\API\Serializer\File\PublicFileSerializer'
           - '@Claroline\AppBundle\Persistence\ObjectManager'

    Claroline\CoreBundle\API\Serializer\Tool\ToolSerializer:
        tags: [claroline.serializer]

    Claroline\CoreBundle\API\Serializer\Template\TemplateTypeSerializer:
        tags: [claroline.serializer]

    Claroline\CoreBundle\API\Serializer\Template\TemplateSerializer:
        tags: [claroline.serializer]
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\CoreBundle\API\Serializer\ParametersSerializer'
            - '@Claroline\AppBundle\API\SerializerProvider'

    Claroline\CoreBundle\API\Serializer\Task\ScheduledTaskSerializer:
        tags: [claroline.serializer]
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\CoreBundle\API\Serializer\Workspace\WorkspaceSerializer'
            - '@Claroline\CoreBundle\API\Serializer\User\UserSerializer'

    Claroline\CoreBundle\API\Serializer\Resource\ResourceUserEvaluationSerializer:
        tags: [claroline.serializer]
        arguments:
            - '@Claroline\CoreBundle\API\Serializer\Resource\ResourceNodeSerializer'
            - '@Claroline\CoreBundle\API\Serializer\User\UserSerializer'

    Claroline\CoreBundle\API\Serializer\Resource\ResourceTypeSerializer:
        tags: [claroline.serializer]
        arguments:
            - '@claroline.manager.resource_action'

    Claroline\CoreBundle\API\Serializer\Resource\ResourceNodeSerializer:
        tags: [claroline.serializer]
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\AppBundle\Event\StrictDispatcher'
            - '@Claroline\CoreBundle\API\Serializer\File\PublicFileSerializer'
            - '@Claroline\CoreBundle\API\Serializer\User\UserSerializer'
            - '@claroline.manager.mask_manager'
            - '@claroline.manager.optimized_rights_manager'
            - '@claroline.manager.rights_manager'
            - '@Claroline\AppBundle\API\SerializerProvider'

    Claroline\CoreBundle\API\Serializer\Resource\ResourceEvaluationSerializer:
        tags: [claroline.serializer]
        arguments:
            - '@Claroline\CoreBundle\API\Serializer\Resource\ResourceUserEvaluationSerializer'

    Claroline\CoreBundle\API\Serializer\Resource\ResourceCommentSerializer:
        tags: [claroline.serializer]
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\CoreBundle\API\Serializer\User\UserSerializer'

    Claroline\CoreBundle\API\Serializer\Resource\Types\TextSerializer:
        tags: [claroline.serializer]
        arguments:
            - '@security.token_storage'

    Claroline\CoreBundle\API\Serializer\Resource\Types\FileSerializer:
        tags: [claroline.serializer]
        arguments:
            - '@router'
            - '%claroline.param.files_directory%'
            - '@event_dispatcher'

    Claroline\CoreBundle\API\Serializer\Resource\Types\DirectorySerializer:
        tags: [claroline.serializer]

    Claroline\CoreBundle\API\Serializer\Platform\ThemeSerializer:
        tags: [claroline.serializer]
        arguments:
            - '@Claroline\CoreBundle\Library\Configuration\PlatformConfigurationHandler'
            - '@Claroline\CoreBundle\API\Serializer\User\UserSerializer'

    Claroline\CoreBundle\API\Serializer\Platform\PluginSerializer:
        tags: [claroline.serializer]

    Claroline\CoreBundle\API\Serializer\Platform\ClientSerializer:
        arguments:
            - '%kernel.environment%'
            - '@assets.packages'
            - '@event_dispatcher'
            - '@security.token_storage'
            - '@request_stack'
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@router'
            - '@Claroline\CoreBundle\Library\Configuration\PlatformConfigurationHandler'
            - '@claroline.manager.version_manager'
            - '@claroline.manager.plugin_manager'
            - '@claroline.manager.icon_set_manager'
            - '@Claroline\CoreBundle\API\Serializer\Resource\ResourceTypeSerializer'
            - '@Claroline\AuthenticationBundle\Manager\OauthManager'

    Claroline\CoreBundle\API\Serializer\Log\LogSerializer:
        tags: [claroline.serializer]
        arguments:
            - '@translator'
            - '@event_dispatcher'

    Claroline\CoreBundle\API\Serializer\Log\Connection\LogConnectWorkspaceSerializer:
        tags: [claroline.serializer]
        arguments:
            - '@Claroline\AppBundle\API\SerializerProvider'

    Claroline\CoreBundle\API\Serializer\Log\Connection\LogConnectToolSerializer:
        tags: [claroline.serializer]
        arguments:
            - '@Claroline\AppBundle\API\SerializerProvider'

    Claroline\CoreBundle\API\Serializer\Log\Connection\LogConnectResourceSerializer:
        tags: [claroline.serializer]
        arguments:
            - '@Claroline\AppBundle\API\SerializerProvider'

    Claroline\CoreBundle\API\Serializer\Log\Connection\LogConnectPlatformSerializer:
        tags: [claroline.serializer]
        arguments:
            - '@Claroline\AppBundle\API\SerializerProvider'

    Claroline\CoreBundle\API\Serializer\Log\Connection\LogConnectAdminToolSerializer:
        tags: [claroline.serializer]
        arguments:
            - '@Claroline\AppBundle\API\SerializerProvider'

    Claroline\CoreBundle\API\Serializer\File\PublicFileSerializer:
        tags: [claroline.serializer]
        arguments:
            - '@Claroline\CoreBundle\Library\Utilities\FileUtilities'

    Claroline\CoreBundle\API\Serializer\Facet\PanelFacetSerializer:
        tags: [claroline.serializer]
        arguments:
            - '@Claroline\CoreBundle\API\Serializer\User\RoleSerializer'
            - '@Claroline\CoreBundle\API\Serializer\Facet\FieldFacetSerializer'

    Claroline\CoreBundle\API\Serializer\Facet\FieldFacetValueSerializer:
        tags: [claroline.serializer]
        arguments:
            - '@Claroline\CoreBundle\API\Serializer\Facet\FieldFacetSerializer'
            - '@service_container'

    Claroline\CoreBundle\API\Serializer\Facet\FieldFacetSerializer:
        tags: [claroline.serializer]
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\CoreBundle\API\Serializer\Facet\FieldFacetChoiceSerializer'

    Claroline\CoreBundle\API\Serializer\Facet\FieldFacetChoiceSerializer:
        tags: [claroline.serializer]

    Claroline\CoreBundle\API\Serializer\Facet\FacetSerializer:
        tags: [claroline.serializer]
        arguments:
            - '@Claroline\CoreBundle\API\Serializer\User\RoleSerializer'
            - '@Claroline\CoreBundle\API\Serializer\Facet\PanelFacetSerializer'

    Claroline\CoreBundle\API\Serializer\Cryptography\ApiTokenSerializer:
        tags: [claroline.serializer]
        arguments:
            - '@Claroline\CoreBundle\API\Serializer\User\UserSerializer'
            - '@Claroline\AppBundle\Persistence\ObjectManager'

    Claroline\CoreBundle\API\Serializer\ConnectionMessage\ConnectionMessageSerializer:
        tags: [claroline.serializer]
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\CoreBundle\API\Serializer\User\RoleSerializer'
