services:
    _defaults:
        autowire: false
        autoconfigure: true
        public: false

    Claroline\CoreBundle\API\Serializer\ParametersSerializer:
        arguments:
          - '@claroline.api.serializer'
          - '@claroline.api.finder'
          - '@claroline.manager.icon_set_manager'
          - '@claroline.persistence.object_manager'
          - '@claroline.config.platform_config_handler'
          - '%claroline.param.platform_options%'
          - '%claroline.param.archive_directory%'

    claroline.serializer.parameters:
        alias: Claroline\CoreBundle\API\Serializer\ParametersSerializer
        public: true

    Claroline\CoreBundle\API\Serializer\ObjectLockSerializer:
        tags: [claroline.serializer]
        arguments:
          - '@claroline.serializer.user'

    claroline.serializer.object_lock:
        alias: Claroline\CoreBundle\API\Serializer\ObjectLockSerializer
        public: true

    Claroline\CoreBundle\API\Serializer\MessageSerializer:
        arguments:
          - '@claroline.serializer.user'

    claroline.serializer.message:
        alias: Claroline\CoreBundle\API\Serializer\MessageSerializer
        public: true

    Claroline\CoreBundle\API\Serializer\DataSourceSerializer:
        tags: [claroline.serializer]

    claroline.serializer.data_source:
        alias: Claroline\CoreBundle\API\Serializer\DataSourceSerializer
        public: true

    Claroline\CoreBundle\API\Serializer\AdminToolSerializer:
        tags: [claroline.serializer]

    claroline.serializer.admin_tool:
        alias: Claroline\CoreBundle\API\Serializer\AdminToolSerializer
        public: true

    Claroline\CoreBundle\API\Serializer\Workspace\WorkspaceSerializer:
        tags: [claroline.serializer]
        arguments:
          - '@security.authorization_checker'
          - '@security.token_storage'
          - '@claroline.persistence.object_manager'
          - '@claroline.manager.workspace_manager'
          - '@claroline.manager.resource_manager'
          - '@claroline.utilities.misc'
          - '@claroline.utilities.file'
          - '@claroline.api.finder'
          - '@claroline.serializer.user'
          - '@claroline.serializer.public_file'
          - '@claroline.serializer.resource_node'

    claroline.serializer.workspace:
        alias: Claroline\CoreBundle\API\Serializer\Workspace\WorkspaceSerializer
        public: true

    Claroline\CoreBundle\API\Serializer\Workspace\ShortcutsSerializer:
        tags: [claroline.serializer]
        arguments:
            - '@claroline.serializer.role'

    Claroline\CoreBundle\API\Serializer\Workspace\PendingRegistrationSerializer:
        tags: [claroline.serializer]
        arguments:
            - '@claroline.serializer.user'

    claroline.serializer.pending:
        alias: Claroline\CoreBundle\API\Serializer\Workspace\PendingRegistrationSerializer
        public: true

    Claroline\CoreBundle\API\Serializer\Widget\WidgetSerializer:
        tags: [claroline.serializer]

    claroline.serializer.widget:
        alias: Claroline\CoreBundle\API\Serializer\Widget\WidgetSerializer
        public: true

    Claroline\CoreBundle\API\Serializer\Widget\WidgetSerializer:
        tags: [claroline.serializer]

    claroline.serializer.widget:
        alias: Claroline\CoreBundle\API\Serializer\Widget\WidgetSerializer
        public: true

    Claroline\CoreBundle\API\Serializer\Widget\WidgetInstanceSerializer:
        tags: [claroline.serializer]
        arguments:
            - '@claroline.persistence.object_manager'
            - '@claroline.api.serializer'

    claroline.serializer.widget_instance:
        alias: Claroline\CoreBundle\API\Serializer\Widget\WidgetInstanceSerializer
        public: true

    Claroline\CoreBundle\API\Serializer\Widget\WidgetContainerSerializer:
        tags: [claroline.serializer]
        arguments:
            - '@claroline.persistence.object_manager'
            - '@claroline.api.finder.widget_instance'
            - '@claroline.serializer.widget_instance'
            - '@claroline.serializer.public_file'

    claroline.serializer.widget_container:
        alias: Claroline\CoreBundle\API\Serializer\Widget\WidgetContainerSerializer
        public: true

    Claroline\CoreBundle\API\Serializer\Widget\HomeTabSerializer:
        tags: [claroline.serializer]
        arguments:
            - '@claroline.persistence.object_manager'
            - '@claroline.api.finder.widget_instance'
            - '@claroline.serializer.widget_instance'
            - '@claroline.serializer.public_file'
            - '@claroline.serializer.workspace'
            - '@claroline.serializer.user'
            - '@claroline.serializer.public_file'

    claroline.serializer.home_tab:
        alias: Claroline\CoreBundle\API\Serializer\Widget\HomeTabSerializer
        public: true

    Claroline\CoreBundle\API\Serializer\Widget\Type\SimpleWidgetSerializer:
        tags: [claroline.serializer]

    claroline.serializer.widget_simple:
        alias: Claroline\CoreBundle\API\Serializer\Widget\Type\SimpleWidgetSerializer
        public: true

    Claroline\CoreBundle\API\Serializer\Widget\Type\ResourceWidgetSerializer:
        tags: [claroline.serializer]
        arguments:
            - '@claroline.persistence.object_manager'
            - '@claroline.serializer.resource_node'

    claroline.serializer.widget_resource:
        alias: Claroline\CoreBundle\API\Serializer\Widget\Type\ResourceWidgetSerializer
        public: true

    Claroline\CoreBundle\API\Serializer\Widget\Type\ProgressionWidgetSerializer:
        tags: [claroline.serializer]

    claroline.serializer.widget_progression:
        alias: Claroline\CoreBundle\API\Serializer\Widget\Type\ProgressionWidgetSerializer
        public: true

    Claroline\CoreBundle\API\Serializer\Widget\Type\ResourceWidgetSerializer:
        tags: [claroline.serializer]
        arguments:
            - '@security.token_storage'
            - '@claroline.serializer.user'

    claroline.serializer.widget_profile:
        alias: Claroline\CoreBundle\API\Serializer\Widget\Type\ResourceWidgetSerializer
        public: true

    Claroline\CoreBundle\API\Serializer\Widget\Type\ListWidgetSerializer:
        tags: [claroline.serializer]

    claroline.serializer.widget_list:
        alias: Claroline\CoreBundle\API\Serializer\Widget\Type\ListWidgetSerializer
        public: true
