services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: true

  _instanceof:
      Claroline\AppBundle\API\ValidatorInterface:
          tags: [claroline.validator]

    Claroline\CoreBundle\API\Validator\WorkspaceValidator:
        arguments:
          - '@claroline.persistence.object_manager'

    Claroline\CoreBundle\API\Validator\UserValidator:
        arguments:
          - '@claroline.persistence.object_manager'
          - '@claroline.serializer.profile'

    Claroline\CoreBundle\API\Validator\GroupValidator:
        arguments:
          - '@claroline.persistence.object_manager'

    Claroline\CoreBundle\API\Validator\Resource\ResourceNodeValidator:
        arguments:
          - '@claroline.persistence.object_manager'
