parameters:
    claroline.migration_manager.class:     Claroline\MigrationBundle\Manager\Manager
    claroline.migration_generator.class:   Claroline\MigrationBundle\Generator\Generator
    claroline.migration_writer.class:      Claroline\MigrationBundle\Generator\Writer
    claroline.migration_migrator.class:    Claroline\MigrationBundle\Migrator\Migrator
    claroline.migration_schema_tool.class: Doctrine\ORM\Tools\SchemaTool
