services:

    Claroline\ThemeBundle\Command\CreateThemeCommand:
        arguments:
            - '@claroline.manager.theme_manager'
        tags:
            - { name: 'console.command', command: 'claroline:theme:create' }

    Claroline\ThemeBundle\Command\BuildThemesCommand:
        arguments:
            - '@claroline.manager.theme_builder'
            - '@claroline.manager.theme_manager'
        tags:
            - { name: 'console.command', command: 'claroline:theme:build' }
