services:
    _defaults:
        autowire: false #change to true
        autoconfigure: false
        public: true #because controller

    _instanceof:
        Claroline\AppBundle\Controller\AbstractCrudController:
            calls:
              - method: setFinder
                arguments:
                  - '@Claroline\AppBundle\API\FinderProvider'
              - method: setSerializer
                arguments:
                  - '@Claroline\AppBundle\API\SerializerProvider'
              - method: setCrud
                arguments:
                  - '@Claroline\AppBundle\API\Crud'
              - method: setObjectManager
                arguments:
                  - '@Claroline\AppBundle\Persistence\ObjectManager'
              - method: setRouterFinder
                arguments:
                  - '@Claroline\AppBundle\Routing\Finder'
              - method: setRouterDocumentator
                arguments:
                  - '@Claroline\AppBundle\Routing\Documentator'
              - method: setContainer
                arguments:
                  - '@service_container'

    Claroline\CoreBundle\Controller\ThemeController: ~

    Claroline\ThemeBundle\Controller\ColorCollectionController: ~

    Claroline\ThemeBundle\Controller\IconController:
        arguments:
          - '%kernel.project_dir%'

    Claroline\ThemeBundle\Controller\Icon\IconSetController: ~

    Claroline\ThemeBundle\Controller\Icon\IconItemController:
        arguments:
          - '@security.authorization_checker'
          - '@Claroline\ThemeBundle\Manager\IconSetManager'
          - '@claroline.manager.tool_manager'
