services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: true

    Claroline\ThemeBundle\Listener\Platform\ClientListener:
        arguments:
            - '@Claroline\CoreBundle\Library\Configuration\PlatformConfigurationHandler'
            - '@Claroline\ThemeBundle\Manager\IconSetManager'
        tags:
            - { name: kernel.event_listener, event: claroline_populate_client_config, method: onConfig }
