services:
    _defaults:
        autoconfigure: false
        public: false

    Claroline\ThemeBundle\Manager\ThemeManager:
        arguments:
          - '@Claroline\AppBundle\Persistence\ObjectManager'
          - '@security.authorization_checker'
          - '@Claroline\CoreBundle\Library\Configuration\PlatformConfigurationHandler'
          - '%kernel.root_dir%'
          - '@Claroline\CoreBundle\API\Serializer\Platform\ThemeSerializer'
          - '@claroline.manager.plugin_manager'

    claroline.manager.theme_manager:
        alias: Claroline\ThemeBundle\Manager\ThemeManager
        public: true

    Claroline\ThemeBundle\Manager\ThemeBuilderManager:
        arguments:
          - '@kernel'
          - '%claroline.param.files_directory%'
          - '%kernel.root_dir%'

    claroline.manager.theme_builder:
        alias: Claroline\ThemeBundle\Manager\ThemeBuilderManager
        public: true
