services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: true

    Claroline\ThemeBundle\Serializer\ThemeSerializer:
        tags: [claroline.serializer]
        arguments:
            - '@Claroline\CoreBundle\Library\Configuration\PlatformConfigurationHandler'
            - '@Claroline\CoreBundle\API\Serializer\User\UserSerializer'

    Claroline\ThemeBundle\Serializer\Icon\IconSetSerializer:
        tags: [claroline.serializer]

    Claroline\ThemeBundle\Serializer\Icon\IconItemSerializer:
        tags: [claroline.serializer]
        arguments:
            - '@Claroline\ThemeBundle\Serializer\Icon\IconSetSerializer'
