const RULE_RESOURCE_PASSED = 'resource_passed'
const RULE_RESOURCE_SCORE_ABOVE = 'resource_score_above'
const RULE_RESOURCE_COMPLETED_ABOVE = 'resource_completed_above'
const RULE_WORKSPACE_PASSED = 'workspace_passed'
const RULE_WORKSPACE_SCORE_ABOVE = 'workspace_score_above'
const RULE_WORKSPACE_COMPLETED_ABOVE = 'workspace_completed_above'
const RULE_RESOURCE_PARTICIPATED = 'resource_participated'
const RULE_IN_GROUP_OR_ROLE = 'user_in_group_or_role'
const RULE_PROFILE_COMPLETED = 'profile_completed'

export {
  RULE_RESOURCE_PASSED,
  RULE_RESOURCE_SCORE_ABOVE,
  RULE_RESOURCE_COMPLETED_ABOVE,
  RULE_WORKSPACE_PASSED,
  RULE_WORKSPACE_SCORE_ABOVE,
  RULE_WORKSPACE_COMPLETED_ABOVE,
  RULE_RESOURCE_PARTICIPATED,
  RULE_IN_GROUP_OR_ROLE,
  RULE_PROFILE_COMPLETED
}
