# This file gathers container configuration that must be loaded at the application level

parameters:
    security.exception_listener.class: Claroline\CoreBundle\Library\Security\Firewall\ExceptionListener
    security.logout.handler.session.class: Claroline\CoreBundle\Library\Security\LogoutHandler
    templating.locator.class: Claroline\CoreBundle\Library\Templating\Loader\TemplateLocator
    twig.controller.exception.class : Claroline\CoreBundle\Controller\CustomExceptionController

services:
    templating.locator:
        class: '%templating.locator.class%'
        arguments:
            - "@file_locator"
            - "@claroline.manager.theme_manager"
            - "%kernel.root_dir%/Resources"

    claroline.honeypot_extension:
        arguments:
            - "@service_container"
        class: Claroline\CoreBundle\Form\Extension\HoneypotExtension
        tags:
            - { name: form.type_extension, alias: form, extended_type: Symfony\Component\Form\Extension\Core\Type\StringType }

framework:
    test: true
