light_saml_symfony_bridge:
    own:
        entity_id: https://test.vd.claroline.com/
        credentials:
            -
                certificate: "%kernel.root_dir%/../saml.crt"
                key:         "%kernel.root_dir%/../saml.pem"
                password:    ~
    party:
        idp:
            files:
                - "https://validation.portail.vd.ch/sso/saml2/jsp/exportmetadata.jsp?entityid=IDP-default_validation.portail.vd.ch&realm=/internet"

    store:
        id_state: 'Claroline\AuthenticationBundle\Security\Saml\IdStore'
