parameters:
    # config is filled with some platform options in ClarolineAuthenticationExtension
    entity_id: 'claroline'
    credentials:
      - certificate: "%kernel.root_dir%/../saml.crt"
        key: "%kernel.root_dir%/../saml.pem"
        password: ~
    idp: []

light_saml_symfony_bridge:
    own:
        entity_id: "%entity_id%"
        entity_descriptor_provider:
            id: Claroline\AuthenticationBundle\Security\Saml\EntityDescriptorProvider
        credentials: "%credentials%"
    party:
        idp:
            files: "%idp%"

    store:
        request: Claroline\AuthenticationBundle\Security\Saml\Store\RequestStateStore
        id_state: Claroline\AuthenticationBundle\Security\Saml\Store\IdStore

security:
    firewalls:
        main:
            # Allows SAML authentication
            logout:
                handlers:
                    - Claroline\AuthenticationBundle\Security\Saml\LogoutHandler

            light_saml_sp:
                provider: user_db # use the standard user provider
                user_creator: Claroline\AuthenticationBundle\Security\Saml\UserCreator
                login_path: /saml/login
                check_path: /saml/login_check
                default_target_path: /
                require_previous_session: false
                success_handler: Claroline\CoreBundle\Listener\AuthenticationSuccessListener
                failure_handler: Claroline\CoreBundle\Listener\AuthenticationFailureHandler
