# This file contains the authentication container parameters.
parameters:
    # IP config files (should be stored in DB)
    claroline.param.ip_white_list_file:       "%claroline.param.config_directory%/ip_white_list.yml"
    claroline.param.ip_range_white_list_file: "%claroline.param.config_directory%/white_list_ip_range.yml"
