hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect
    options:
        expose: true

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

facebook_login:
    path: /login/check-facebook

twitter_login:
    path: /login/check-twitter

google_login:
    path: /login/check-google

linkedin_login:
    path: /login/check-linkedin

windows_live_login:
    path: /login/check-windows

office_365_login:
    path: /login/check-o365

oauth2_generic_login:
    path: /login/check-generic


claro_authentication_api:
    resource: "@ClarolineAuthenticationBundle/Controller/"
    prefix: apiv2
    type: api
    options:
        expose: true
