imports:
    - { resource: services/serializer.yml }
    - { resource: services/controller.yml }
    - { resource: services/configuration.yml }
    - { resource: services/manager.yml }
    - { resource: services/security.yml }
    - { resource: services/listener.yml }
