################################################################
# Default container parameters in test environment (DB settings
# adapted to travis).
################################################################

parameters:

# database
    test_database_driver: pdo_mysql
    test_database_host: localhost
    test_database_port: ~
    test_database_name: claroline_test
    test_database_user: travis
    test_database_password: ~

# mail

    mailer_transport: smtp
    mailer_encryption: ~
    mailer_auth_mode: ~
    mailer_host: ~
    mailer_port: ~
    mailer_user: ~
    mailer_password: ~

# others

    locale: en
    secret: ThisTokenIsNotSoSecretChangeIt

# logs
    non_repeatable_log_time_in_seconds: 600

# Forms
    # Presets for date range picker
    # All possible values:
    # ['today', 'yesterday', 'this_week', 'last_week', 'this_month', 'last_month', 'this_year', 'last_year', 'this_school_year', 'last_school_year', 'last_seven_days', 'last_thirty_days']
    chosenRangeKeys: "['yesterday', 'last_seven_days', 'last_thirty_days', 'this_month', 'last_month', 'this_school_year', 'last_school_year']"
