name: 'Close all issues'
on:
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue is going to be closed because it has no recent activity and the project has been moved to https://github.com/claroline/Claroline. If you think it is still relevant, please consider opening a new issue on https://github.com/claroline/Claroline.'
          days-before-stale: 0
          days-before-close: 0
          exempt-issue-labels: 'Keep Open'
