const EVALUATION_STATUS_PASSED        = 'passed'
const EVALUATION_STATUS_FAILED        = 'failed'
const EVALUATION_STATUS_COMPLETED     = 'completed'
const EVALUATION_STATUS_INCOMPLETE    = 'incomplete'
const EVALUATION_STATUS_NOT_ATTEMPTED = 'not_attempted'
const EVALUATION_STATUS_UNKNOWN       = 'unknown'

export const constants = {
  EVALUATION_STATUS_PASSED,
  EVALUATION_STATUS_FAILED,
  EVALUATION_STATUS_COMPLETED,
  EVALUATION_STATUS_INCOMPLETE,
  EVALUATION_STATUS_NOT_ATTEMPTED,
  EVALUATION_STATUS_UNKNOWN
}
